### ISSUE TITLE
bug: build failing

### ISSUE THREAD

**Issue by maximee-leroyy** [srcdslab/sm-plugin-BoostAlert-discord#6]
```
Build output: ./addons/sourcemod/plugins
Updating...
Updating: sourcemod
 Downloading https://sm.alliedmods.net/smdrop/1.11/sourcemod-1.11.0-git[6](https://github.com/srcdslab/sm-plugin-BoostAlert-discord/actions/runs/12124288100/job/33801678367?pr=5#step:4:7)934-linux.tar.gz...
Updating: discordwebapi
 Cloning from https://github.com/srcdslab/sm-plugin-DiscordWebhookAPI
Updating: BoostAlert
 Cloning from https://github.com/srcdslab/sm-plugin-BoostAlert
Updating: AutoRecorder
 Cloning from https://github.com/srcdslab/sm-plugin-AutoRecorder
Unpacking...
Unpacking sourcemod...
 Unpacking archive...
 Extracting addons to addons
Unpacking discordwebapi...
 Extracting include to addons/sourcemod/scripting/include
Unpacking BoostAlert...
 Extracting include to addons/sourcemod/scripting/include
Error occurred during unpack, removing build tree...
Traceback (most recent call last):
  File "/usr/local/bin/sourceknight", line [8](https://github.com/srcdslab/sm-plugin-BoostAlert-discord/actions/runs/12124288100/job/33801678367?pr=5#step:4:9), in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.[10](https://github.com/srcdslab/sm-plugin-BoostAlert-discord/actions/runs/12124288100/job/33801678367?pr=5#step:4:11)/site-packages/sourceknight/main.py", line 44, in main
    command(ctx)(args)
  File "/usr/local/lib/python3.10/site-packages/sourceknight/build.py", line 28, in __call__
    unpack(self._ctx)(args)
  File "/usr/local/lib/python3.10/site-packages/sourceknight/unpack.py", line 38, in __call__
    dmgr.unpack(self._ctx._state.dependencies[dep['name']], dep['unpack'], fmgr, args.force)
  File "/usr/local/lib/python3.10/site-packages/sourceknight/dependencies.py", line 63, in unpack
    drivers_by_name[d.params['driver']](self._ctx, d).unpack(fmgr, locations)
  File "/usr/local/lib/python3.10/site-packages/sourceknight/drivers/git.py", line 58, in unpack
    shutil.copyfile(src, dst)
  File "/usr/local/lib/python3.10/shutil.py", line [25](https://github.com/srcdslab/sm-plugin-BoostAlert-discord/actions/runs/12124288100/job/33801678367?pr=5#step:4:26)4, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: './.sourceknight/cache/BoostAlert/include'
```

**Comment by Rushaway** [comment]
Fixed in #7
